services:
  app:
    image: cimg/ruby:3.3.0
    working_dir: /app
    depends_on:
      - solr
    tty: true
    volumes:
      - .:/app
      - $PWD/bin/load-data:/bin/load-data
    environment:
      SOLR_URL: "http://solr:8983/solr/blacklight"
      SOLR_DISABLE_UPDATE_DATE_CHECK: "true"
      DO_INGEST: "${DO_INGEST}"
      LC_ALL: "C.UTF-8"
      BUNDLE_PATH: /app/vendor/bundle

  solr:
    image: solr:9.6.1
    volumes:
      - $PWD/bin/solr-configs-reset:/opt/docker-solr/scripts/solr-configs-reset
      - $PWD:/opt/solr/conf/tul_cob-catalog-solr
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - blacklight
      - /opt/solr/conf/tul_cob-catalog-solr
      - "-Xms256m"
      - "-Xmx512m"
