name: Lint and Test

on:
  push:
    branches-ignore:
      - main
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Docker Compose
        run: |
          curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m) > ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - name: Build the app
        run: make up
      - name: Install Solr Documents
        run: make load-data
      - name: Run relevancy Tests
        run: make test

  run_deploy:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is on main
        id: check_main
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG_COMMIT=$(git rev-parse ${{ github.ref }})
          git fetch origin main
          if git branch --contains $TAG_COMMIT | grep 'main'; then
            echo "on_main=true" >> $GITHUB_OUTPUT
          else
            echo "on_main=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy
        if: github.ref_type != 'tag' || steps.check_main.outputs.on_main == 'true'
        run: echo "Deploying (either not a tag, or tag is on main)"

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build configuration asset
        run: make zip
      - name: Deploy configuration asset to SolrCloud
        env:
          TAG_NAME: ${{ github.ref_name }}
          SOLR_USER: ${{ secrets.SOLR_USER }}
          SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .circleci/deploy.sh
